# Numpy

- Numeriacal Python

- 파이썬 머신러닝 패키지인 scikit-learn에서 기본 데이터 구조로 사용되어 Numpy 배열 형태의 데이터를 사용

- 파이썬 기반 데이터 분석 환경에서 행렬 및 벡터 연산에 필요한 다양한 함수를 제공

- 메모리 소모가 많은 반복문 없이 전체 데이터 배열에 빠른 연산을 처리할 수 있는 표준 수학 함수

> 배열 : 동일한 특성(데이터 타입) 및 일정한 규칙을 가지는 여러 개의 요소가 나열되어 있는 데이터 집합

- 파이썬 list 객체를 사용할 때 보다 Numpy의 ndarray 객체를 사용하면 연산 속도가 개선되어 더 많은 데이터를 더 빠르게 처리

In [1]:
# 라이브러리 가져오기 : Numpy
# as 별칭 선언 이후에는 별칭으로 해당 라이브러리의 기능을 쓸 수 있다.
# import 라이브러리명 as 별칭
import numpy as np

In [2]:
np.__version__

'1.18.1'

## Numpy 배열 : numpy.ndarray

- 다차원 배열(1차원, 2차원, 3차원)으로 입체적인 데이터 구조를 구성하고 여러 개의 데이터 방향을 가진다.

- 배열 속성 : shape, ndim, dtype 등

- 데이터 방향 : axis = 0(행/높이), 1(열/폭), 2(채널/깊이)

사진을 집어넣을때는 img태그 를 사용합니다.
<img src='img/nparr1.jpg' width='600' height='400' align='left'>

### 1. 배열 생성

- np.array(data)

    - 파이썬 list객체를 전달받아 numpy list로 교환해주는 명령어
    
    - 배열 속성
        - shape : 구조 (행, 열, 차원)
        - ndim : 차원
        - dtype : 데이터 타입
        - size : 요소 개수 = 행 * 열 * 차원
        
    - 배열 메서드
        - astype() : 데이터 타입 변환(문자를 숫자로 라던지...)
        
    - 파이썬 내장함수를 사용한 속성값
        - type() : 객체의 자료형 확인
        - len() : 요소 내부의 자료 길이.
        
    - Numpy 함수를 사용한 속성
        - reshape(row, column) : 배열 재배치(1 * 12를 3 * 4 형태로 바꾼다던지...)
        
    - kind : 데이터 종류에 대한 구분 기호
        - b boolean
        - i 정수(int)
        - u 부호없는 정수(unsigned int, +- 개념 없이 절대값만 존재)
        - f 실수
        - c 복소 부동소수점
        - O 객체
        - S 바이트 문자열(ascii 코드, 영문자, 일부특문, 숫자)
        - U 유니코드 문자열(한글, 중국어, 태국어, 아랍어 등 영어와 다른 문자)

In [3]:
# 파이썬 1차원 리스트를 Numpy로 교환하기
tmp = [1,2,3,4,5,6]
arr = np.array(tmp)
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
# 배열 객체의 속성 - 타입(자료형)
print(type(arr),type(tmp))

<class 'numpy.ndarray'> <class 'list'>


In [13]:
# 배열 객체의 속성 : 구조 확인하기 -shape (행(row), 열(column), 차원(면))
# (정수, ): 정수 갯수의 아이템을 가진 리스트가 배열로 변환된 결과물
arr.shape

(6,)

In [14]:
len(arr)

6

In [16]:
# 배열 객체의 속성 - 차원
arr.ndim

1

In [17]:
# 배열 요소의 속성 - 데이터 타입
arr.dtype

dtype('int32')

In [18]:
# 배열 객체의 속성 - 데이터 타입의 변환 : astype => 원본 데이터 유지
arr2 = arr.astype(float)

In [19]:
print(arr.dtype,arr2.dtype)

int32 float64


In [21]:
# 배열 구조 변환
# 기본 배열의 요소 총 개수(6개)와 변환하려는 구조의 총 개수(6개)는 일치해야 한다.
arr.reshape(2,3) #(2 x 3 이 6이므로),reshape(row,column)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# Numpy 객체 정보를 좀 더 편하게 확인하기 위한 사용자 함수 정의
# 객체타입, 구조, 차원, 데이터타입, 내부자료
# 를 확인하기 위해 정의하는 함수
def np_print(arr):
    text = '''
    type : {}
    shape : {}
    ndim : {}
    dtype : {}
    array data : \n {}'''.format(type(arr),arr.shape,arr.ndim,arr.dtype,arr)
    print(text)

In [24]:
np_print(np.array([1,2,3,4,5]))


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : int32
    array data : 
 [1 2 3 4 5]


In [27]:
# 리스트 요소 타입이 일관되지 않으면 우선순위에 따라 내부 데이터의 dtype이 통일된다.
# 우선순위 : str(가장 높음) > float > int(가장 낮음)
# 서로 다른 타입의 혼합 1: int +str = str
tmp = [1,2,3,'4']
arr1 = np.array(tmp)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (4,)
    ndim : 1
    dtype : <U11
    array data : 
 ['1' '2' '3' '4']


In [29]:
tmp = [1,2,3.3,4]
arr = np.array(tmp)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (4,)
    ndim : 1
    dtype : float64
    array data : 
 [1.  2.  3.3 4. ]


In [30]:
# 파이썬 2차원 리스트 Numpy 배열 생성
# 2차원 배열의 shape 속성은 (행(row),열(column))
tmp = [[1,2,3,4],
      [5,6,7,8]]
arr = np.array(tmp)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (2, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3 4]
 [5 6 7 8]]


In [31]:
# 파이썬 3차원 리스트로 numpy 배열 생성
tmp = [[[1,2,3],[4,5,6]],
      [[7,8,9],[10,11,12]]]
arr = np.array(tmp)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (2, 2, 3)
    ndim : 3
    dtype : int32
    array data : 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [35]:
# 데이터 타입을 파라미터로 지정해서 Numpy배열 타입 속성을 바꿔줄 수 있다.
# np.array(data,dtype='자료형')
tmp = [[[1,2,3],[4,5,6]],
      [[7,8,9],[10,11,12]]]
arr = np.array(tmp,dtype='float')
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (2, 2, 3)
    ndim : 3
    dtype : float64
    array data : 
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


### 생성 및 초기화

1. 초기값을 지정하여 데이터를 자동으로 가지는 배열을 생성

    - np.zeros()
    - np.ones()
    - np.full()
    - np.eye()
    - np.empty()

#### 1-1. np.zeros(shape(모양), dtype=float)

- 지정된 구조의 배열을 생성하고 모든 요소를 0으로 초기화(zeros)
- shape : tuple형태로 행, 열을 지정
- dtype : 배열에서 사용하는 데이터 타입을 지정, 기본값은 numpy.float64

In [36]:
# 3행 4열 구조 안에서 모든 값이 0으로 채워짐
# 구조는 튜플로 넘겨야 함
arr = np.zeros((3,4))
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : float64
    array data : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
# dtype만 int로 바꿔서 생성
arr = np.zeros((3,4),dtype='int')
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### 1-2. np.ones(shape(행, 열), dtype=float)
- 지정된 구조의 배열을 생성하고 모든 요소를 1로(ones) 초기화.
- shape : tuple 자료로 행, 열 구조를 지정
- dtype : 배열의 데이터 타입을 지정, 기본값 = numpy.float64

In [41]:
# 3행 4열 구조 안에서 초기값을 모두 1로 가지는 배열
arr = np.ones((3,4))
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : float64
    array data : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 1-3. np.full(shape, fill_value, dtype)
- 지정된 구조의 배열을 생성하고 모든 요소를 fill_value 값으로 초기화
- shape : tuple 자료형으로 행, 열 구조를 지정
- dtype = 배열의 데이터 타입을 지정, 기본값 = 들어오는 데이터의 자료형

In [44]:
# 3행 4열 구조 안에서 초기값을 모두 5로 가지는 배열
arr = np.full((3,4),5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


#### 1-4. np.eye(N, M=None, dtype=float)
- (N,M) 구조의 단위 행렬을 생성
- M : 열 개수를 지정, 기본값 = N
- dtype : 배열의 데이터 타입을 지정, 기본값 = numpy.float64

In [45]:
# 3행 3열의 단위행렬
arr = np.eye(3)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : float64
    array data : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 1-5. np.empty(shape, dtype=float)

- 지정된 구조의 배열을 생성하고 모든 요소에 대한 초기화 과정 없이 직전 메모리에 저장된 값을 사용

- 배열을 생성하는데 가장 빠르고 효율적인 방법

- shape : tuple type으로 행,열 구조를 지정

- dtype : 배열의 데이터 타입을 지정, 기본값 = numpy.float64

In [46]:
# 직전에 메모리에 저장된 값을 사용하기 위해서는 직전에 만들었던 것과 동일한
# shape의 배열을 생성해야 한다.
# 3행 4열의 구조
arr = np.empty((3,4))
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : float64
    array data : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### like 함수

- 전달받은 배열과 동일한 shape으로 초기값을 설정하여 새로운 배열을 생성
    
    - np.zeros_like() : 초기값을 0으로 가지는 배열 생성
    
    - np.ones_like() : 초기값을 1로 가지는 배열 생성
    
    - np.full_like() : 초기값을 fill_value 값으로 가지는 배열 생성

In [48]:
# ones_like()
# 2행 3열의 구조에서 1~6의 숫자로 구성된 배열
data = [[1,2,3],[4,5,6]]
arr1 = np.array(data)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (2, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3]
 [4 5 6]]


In [49]:
arr2 = np.ones_like(arr1)
np_print(arr2)


    type : <class 'numpy.ndarray'>
    shape : (2, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 1 1]
 [1 1 1]]


In [50]:
arr3 = np.zeros_like(arr1)
np_print(arr3)


    type : <class 'numpy.ndarray'>
    shape : (2, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[0 0 0]
 [0 0 0]]


In [52]:
arr4 = np.full_like(arr1,4)
np_print(arr4)


    type : <class 'numpy.ndarray'>
    shape : (2, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[4 4 4]
 [4 4 4]]


### Ⅱ. 배열 생성 및 초기화

2. 범위와 조건이 있는 데이터를 가지는 1차원 배열 생성
    - np.linspace()
    
    - np.arange()
    
    - np.logspace()

#### 2-1. np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

- 시작값(start)부터 마지막값(그만) 사이의 범위에서 균등한 간격으로 일정 개수(num)개의 데이터를 가지는 배열 생성

- num : 데이터 개수, 기본값 = 50

- endpoint : 마지막값에 stop을 포함/제외하는 조건 지정, 기본값 = True(포함)

- retstep : True로 전달하면 (배열, 데이터 사이의 간격)의 데이터를 담은 tuple을 반환

- dtype : 배열의 데이터 타입을 지정, 기본값 = None

In [55]:
arr = np.linspace(0,1,5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : float64
    array data : 
 [0.   0.25 0.5  0.75 1.  ]


In [56]:
# endpoint를 False로 변환
arr = np.linspace(0,1,5,endpoint=False)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : float64
    array data : 
 [0.  0.2 0.4 0.6 0.8]


In [58]:
# retstep 설정 -> 반환값 tuple => (배열객체,간격값)
arr = np.linspace(0,1,5,retstep=True)
print(arr)
np_print(arr[0])

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25)

    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : float64
    array data : 
 [0.   0.25 0.5  0.75 1.  ]


#### 2-1. np.arange(start=0, stop, step=1,  dtype=None)

- 시작값(start)부터 마지막값(그만) 사이의 범위에서 지정한 간격(step)으로 일정 개수(num)개의 데이터를 가지는 배열 생성
- 파이썬 내장함수 range()와 유사
- start : 시작값, 기본값 = 0    
- stop : 마지막값으로 범위에 포함되지 않음    
- step : 데이터 사이의 간격, 기본값 = 1
- dtype : 배열의 데이터 타입을 지정, 기본값 = None

In [61]:
list(range(5))

[0, 1, 2, 3, 4]

In [62]:
# 기본값
# 0이상 5미만의 범위에서 1씩 증가하는 숫자(정수)를 가지는 배열
arr = np.arange(5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : int32
    array data : 
 [0 1 2 3 4]


In [63]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [64]:
# 시작, 끝, 간격
# 0이상 5미만의 범위에서 0.5씩 증가하는 숫자를 가지는 배열
arr = np.arange(0,5,0.5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (10,)
    ndim : 1
    dtype : float64
    array data : 
 [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [65]:
# arange() 메서드로 생성된 배열과 shape(1,5)인 배열은 동일해 보이지만
# shape와 dimension이 서로 다르다
arr = np.arange(1,5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (4,)
    ndim : 1
    dtype : int32
    array data : 
 [1 2 3 4]


In [66]:
arr2 = arr.reshape(1,4)
np_print(arr2)


    type : <class 'numpy.ndarray'>
    shape : (1, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3 4]]


#### 2-3. np.logspace(start, stop, num=50, endpoint=True, dtype=None)

- 시작값(start)부터 마지막값(그만) 사이의 로그 스케일로 지정된 범위에서 균등한 간격으로 일정 개수(num)개의 데이터를 가지는 배열 생성

- num : 데이터 개수, 기본값 = 50

- endpoint : 마지막 값에 stop을 포함/제외하는 조건 지정, 기본값 = True(포함)

- dtype : 배열의 데이터 타입을 지정, 기본값 = None

In [70]:
# 기본값
# 0이상 1이하의 범위에서 로그스케일을 적용한 값(50개)를 가진 배열
# 밑수가 10인 로그를 기준으로 만들어줌
arr = np.logspace(0,1)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (50,)
    ndim : 1
    dtype : float64
    array data : 
 [ 1.          1.04811313  1.09854114  1.1513954   1.20679264  1.26485522
  1.32571137  1.38949549  1.45634848  1.52641797  1.59985872  1.67683294
  1.75751062  1.84206997  1.93069773  2.02358965  2.12095089  2.22299648
  2.32995181  2.44205309  2.55954792  2.6826958   2.8117687   2.9470517
  3.0888436   3.23745754  3.39322177  3.55648031  3.72759372  3.90693994
  4.09491506  4.29193426  4.49843267  4.71486636  4.94171336  5.17947468
  5.42867544  5.68986603  5.96362332  6.25055193  6.55128557  6.86648845
  7.19685673  7.54312006  7.90604321  8.28642773  8.68511374  9.10298178
  9.54095476 10.        ]
